// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAxB5Pdbtrj_8Ewzay-EJyo2K1kj6ZwG6k',
    appId: '1:322754486531:web:913dcca69cbadf263f4936',
    messagingSenderId: '322754486531',
    projectId: 'etucampusapp',
    authDomain: 'etucampusapp.firebaseapp.com',
    storageBucket: 'etucampusapp.firebasestorage.app',
    measurementId: 'G-YYWGJ7XD98',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCPCILp9okY3RP9LTrXeEiwbVMRsM1m-_I',
    appId: '1:322754486531:android:0f1dd094e896376c3f4936',
    messagingSenderId: '322754486531',
    projectId: 'etucampusapp',
    storageBucket: 'etucampusapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAITGpH0j1T0YOMEXICgEMvWGUAnkivtf0',
    appId: '1:322754486531:ios:bb97109a04a140313f4936',
    messagingSenderId: '322754486531',
    projectId: 'etucampusapp',
    storageBucket: 'etucampusapp.firebasestorage.app',
    androidClientId: '322754486531-gsh5tivhoceeaf2r4mvlqu7tpvtnskhq.apps.googleusercontent.com',
    iosClientId: '322754486531-umqh0jun2kotkm8dj8puf9nmgcu7hjo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.erzurumKampus',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAITGpH0j1T0YOMEXICgEMvWGUAnkivtf0',
    appId: '1:322754486531:ios:bb97109a04a140313f4936',
    messagingSenderId: '322754486531',
    projectId: 'etucampusapp',
    storageBucket: 'etucampusapp.firebasestorage.app',
    androidClientId: '322754486531-gsh5tivhoceeaf2r4mvlqu7tpvtnskhq.apps.googleusercontent.com',
    iosClientId: '322754486531-umqh0jun2kotkm8dj8puf9nmgcu7hjo2.apps.googleusercontent.com',
    iosBundleId: 'com.example.erzurumKampus',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAxB5Pdbtrj_8Ewzay-EJyo2K1kj6ZwG6k',
    appId: '1:322754486531:web:210cc50f9c0880723f4936',
    messagingSenderId: '322754486531',
    projectId: 'etucampusapp',
    authDomain: 'etucampusapp.firebaseapp.com',
    storageBucket: 'etucampusapp.firebasestorage.app',
    measurementId: 'G-LD92QWM1BW',
  );
}
